### ISSUE TITLE
Error when running (test_short_term)

### ISSUE THREAD

**Issue by Ammola** [facebookresearch/QuaterNet#2]
Hi
I'm getting the following error when I try to run (test_short_term.py) file:
AttributeError: Can't get attribute '_rebuild_tensor_v2' on <module 'torch._utils' from '/home/paperspace/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/_utils.py'>

**Comment by dariopavllo** [comment]
It looks like you are using an older version of PyTorch. Are you sure you are using PyTorch 0.4?
