### ISSUE TITLE
Aren't constant angle joints useful for positional loss?

### ISSUE THREAD

**Issue by Godatplay** [facebookresearch/QuaterNet#3]
From the paper:
> We removed joints with constant angle, yielding a dataset with 26 joints.

Aren't joints with a constant angle typically the end joint of a bone chain, and therefore useful for a positional loss function for evaluating the parent of that joint?

**Comment by dariopavllo** [comment]
Hi, you can see here the list of joints that we removed: https://github.com/facebookresearch/QuaterNet/blob/9d8485b732b0a44b99b6cf4b12d3915703507ddc/long_term/dataset_locomotion.py#L68

They are mostly redundant joints, i.e. joints with the same position as another joint, which do not add any extra information.

**Comment by Godatplay** [comment]
Thanks for the reply and info! I thought there was some part of the model I didn't understand correctly, but didn't realize some of their data was redundant.
