### ISSUE TITLE
Accessing positions instead of rotations ?

### ISSUE THREAD

**Issue by TParcollet** [facebookresearch/QuaterNet#5]
Hey ! Thank you for sharing this project! Any quick fix to work on positions instead of rotations? In the prepare_data_short_term.py script, I can see the comment # No trajectory for H3.6M. Nonetheless, the dataset website says that both rotations and 3D coordinates are available ...

Thank you !

**Comment by dariopavllo** [comment]
Hi, sorry for the late reply!

If I recall correctly, the dataset that we used for this project is a preprocessed version, not the original dataset.

In another repo you can find a version of the dataset with joint positions:
https://github.com/facebookresearch/VideoPose3D/blob/master/DATASETS.md

**Comment by TParcollet** [comment]
I'll check that thank you !
